# Generated by Django 3.1 on 2020-08-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiHomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquitecturaSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquitectura', models.CharField(max_length=50)),
                ('byteorder', models.CharField(max_length=50)),
                ('ncpu', models.IntegerField()),
                ('nhilo', models.IntegerField()),
                ('ncore', models.IntegerField()),
                ('nsocket', models.IntegerField()),
                ('fabricante', models.CharField(max_length=50)),
                ('vmodel', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('maxcpu', models.CharField(max_length=50)),
                ('mincpu', models.CharField(max_length=50)),
                ('bogomips', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeteccionesWifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('nombre', models.CharField(max_length=70)),
                ('fecha_ini', models.IntegerField(blank=True, null=True)),
                ('fecha_fin', models.IntegerField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('rssi_min', models.IntegerField(blank=True, null=True)),
                ('rssi_max', models.IntegerField(blank=True, null=True)),
                ('canal', models.IntegerField(blank=True, null=True)),
                ('ncanales', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, default=1, null=True)),
                ('conocido', models.IntegerField(blank=True, default=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('metros_cuadrados', models.IntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MemoriaSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('swap_total', models.IntegerField()),
                ('usada', models.IntegerField()),
                ('usada_swap', models.IntegerField()),
                ('libre', models.IntegerField()),
                ('libre_swap', models.IntegerField()),
                ('compartida', models.IntegerField()),
                ('compartida_swap', models.IntegerField()),
                ('cache', models.IntegerField()),
                ('cache_swap', models.IntegerField()),
                ('disponible', models.IntegerField()),
                ('disponible_swap', models.IntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StatsDeteccionesWifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField()),
                ('ndetecciones', models.IntegerField()),
                ('nmacs', models.IntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TemperaturaCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30, null=True)),
                ('temperatura', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HumedadTemperaturaExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('habitacion', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitacion', to='apiHomes.habitacion')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
