# Generated by Django 3.1 on 2020-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiHomes', '0002_arquitecturasistema_deteccioneswifi_habitacion_humedadtemperaturaexterna_memoriasistema_statsdetecci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticulasAire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField()),
                ('aqi', models.IntegerField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
